import io
from typing import Tuple, Any, Dict, Union


class UnexpectedConfigurationArgumentsError(Exception):
    args: Tuple[str] = ...


class RequiredConfigurationArgumentsError(Exception):
    args: Tuple[str] = ...


class ConfigurationArgumentsTypeError(Exception):
    key: str = ...
    req: type = ...
    exp: type = ...


class Configuration:
    def __new__(
            cls,
            *,
            api_id: int,
            api_hash: str,
            userbot_phone: str,
            bot_token: str,
            channel_id: int,
            group_id: int
    ) -> Configuration: ...

    @classmethod
    def from_dict(cls, dct: Dict[str, Any]) -> Configuration: ...

    @classmethod
    def from_json(cls, string_or_fp: Union[str, io.IOBase]) -> Configuration: ...

    api_id: int = ...
    api_hash: str = ...
    userbot_phone: str = ...
    bot_token: str = ...
    channel_id: int = ...
    group_id: int = ...
